import { DuckEntity, DuckSpeciesId, WaterRipple, Breadcrumb } from '../types';

/**
 * Draws water ripples and wakes generated by swimming ducks in realistic AR
 */
export function drawWaterRipples(
  ctx: CanvasRenderingContext2D,
  ripples: WaterRipple[],
  width: number,
  height: number
) {
  for (const ripple of ripples) {
    const rx = ripple.x * width;
    const ry = ripple.y * height;
    const radiusX = ripple.radius * width;
    const radiusY = radiusX * (ripple.aspectRatio || 0.42);

    ctx.save();
    ctx.beginPath();
    ctx.ellipse(rx, ry, radiusX, radiusY, 0, 0, Math.PI * 2);

    const strokeColor = ripple.color || `rgba(255, 255, 255, ${(ripple.alpha * 0.75).toFixed(3)})`;
    ctx.strokeStyle = strokeColor;
    ctx.lineWidth = Math.max(0.8, 1.8 * ripple.alpha);
    ctx.stroke();

    // Subtle inner secondary harmonic wave
    ctx.beginPath();
    ctx.ellipse(rx, ry, radiusX * 0.88, radiusY * 0.88, 0, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(186, 230, 253, ${(ripple.alpha * 0.35).toFixed(3)})`;
    ctx.lineWidth = 0.8;
    ctx.stroke();

    ctx.restore();
  }
}

/**
 * Draws floating breadcrumbs with realistic water displacement
 */
export function drawBreadcrumbs(
  ctx: CanvasRenderingContext2D,
  breadcrumbs: Breadcrumb[],
  width: number,
  height: number
) {
  for (const b of breadcrumbs) {
    const bx = b.x * width;
    const by = b.y * height;
    const alpha = Math.max(0, Math.min(1, b.life));

    ctx.save();
    // Meniscus ring around floating crumb
    ctx.beginPath();
    ctx.ellipse(bx, by, 6.5, 3.2, 0, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(254, 240, 138, ${(alpha * 0.55).toFixed(2)})`;
    ctx.lineWidth = 1.2;
    ctx.stroke();

    // Organic crumb flake
    ctx.beginPath();
    ctx.ellipse(bx, by - 0.8, 3.2, 2.2, 0.25, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(217, 119, 6, ${alpha.toFixed(2)})`;
    ctx.fill();

    // Specular highlight on crust
    ctx.beginPath();
    ctx.arc(bx - 0.8, by - 1.4, 0.8, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(254, 243, 199, ${(alpha * 0.9).toFixed(2)})`;
    ctx.fill();
    ctx.restore();
  }
}

/**
 * Renders any of the 5 duck species with photographic realism, true plumage anatomy,
 * iridescent photonic light scattering, and realistic water integration.
 */
export function drawDuck(
  ctx: CanvasRenderingContext2D,
  duck: DuckEntity,
  width: number,
  height: number,
  timeMs: number
) {
  const px = duck.x * width;
  const py = duck.y * height;

  // Authentic wild duck proportions
  let speciesScaleFactor = 1.0;
  if (duck.species === 'teal') speciesScaleFactor = 0.74; // Smallest dabbling duck
  else if (duck.species === 'mallard') speciesScaleFactor = 1.14; // Broad heavy dabbler
  else if (duck.species === 'mandarin') speciesScaleFactor = 0.94;
  else if (duck.species === 'tufted') speciesScaleFactor = 0.88; // Compact diver
  else if (duck.species === 'pochard') speciesScaleFactor = 0.96; // Stocky diving duck

  const scale = (duck.scale || 1.0) * Math.min(width, height) * 0.155 * speciesScaleFactor;

  const isDiving = duck.behavior === 'diving';
  const isSubmerged = duck.behavior === 'submerged';
  const isResurfacing = duck.behavior === 'resurfacing';
  const isDabbling = duck.behavior === 'dabbling';
  const isUpEnding = duck.behavior === 'up_ending'; // Mallard signature

  // Gentle floating buoyancy wave bob
  const waveBob = Math.sin(timeMs * 0.0028 + duck.bobPhase) * (scale * 0.035);
  const headNod = Math.sin(duck.paddlePhase * 2) * (scale * 0.024);

  let renderAlpha = 1.0;
  let diveOffset = 0;
  let pitchTilt = 0;

  if (isDiving) {
    const progress = Math.min(1, (1000 - duck.behaviorTimer) / 1000);
    diveOffset = progress * scale * 0.85;
    pitchTilt = -progress * 1.05;
    renderAlpha = 1.0 - progress * 0.65;
  } else if (isSubmerged) {
    diveOffset = scale * 0.95;
    renderAlpha = 0.28;
  } else if (isResurfacing) {
    const progress = Math.min(1, (600 - duck.behaviorTimer) / 600);
    diveOffset = (1 - progress) * scale * 0.85;
    pitchTilt = (1 - progress) * 0.3;
    renderAlpha = 0.4 + progress * 0.6;
  } else if (isUpEnding) {
    // Authentic dabbling posture: tail tipped up 80 degrees, head searching bottom
    pitchTilt = -1.38;
    diveOffset = scale * 0.16;
  } else if (isDabbling) {
    pitchTilt = -0.42;
  }

  ctx.save();
  ctx.translate(px, py + waveBob + diveOffset);

  const isMovingLeft = Math.cos(duck.angle) < 0;
  ctx.scale(isMovingLeft ? -1 : 1, 1);
  ctx.rotate(pitchTilt * (isMovingLeft ? -1 : 1));
  ctx.globalAlpha = renderAlpha;

  // 1. Realistic Submerged Hull Shadow & Water Reflection
  drawRealisticWaterShadow(ctx, scale, duck.species, duck.gender);

  // 2. Submerged Paddling Webbed Feet (Naturalistic anatomy with phalanges)
  if (!isSubmerged) {
    drawRealisticFeet(ctx, scale, duck.species, duck.paddlePhase, isUpEnding);
  }

  // 3. Photorealistic Body Hull & Layered Plumage
  drawRealisticBody(ctx, scale, duck);

  // 4. Species Unique Anatomical Displays (curled drake curls, Mandarin sails, tufted crest)
  drawRealisticSpeciesAccents(ctx, scale, duck, timeMs);

  // 5. Photorealistic Neck, Head, Liquid Eye & Horn Bill
  drawRealisticHead(ctx, scale, duck, headNod, isDabbling);

  // 6. Waterline Meniscus & Bow Wave with Natural Surface Tension
  drawRealisticWaterline(ctx, scale);

  ctx.restore();
}

/**
 * Photorealistic water shadow and subtle reflection beneath the floating body
 */
function drawRealisticWaterShadow(
  ctx: CanvasRenderingContext2D,
  scale: number,
  species: DuckSpeciesId,
  gender: 'male' | 'female'
) {
  ctx.save();
  // Deep underwater occlusion shadow
  ctx.beginPath();
  ctx.ellipse(0, scale * 0.18, scale * 0.54, scale * 0.14, 0, 0, Math.PI * 2);
  ctx.fillStyle = 'rgba(15, 23, 42, 0.45)';
  ctx.filter = 'blur(4px)';
  ctx.fill();

  // Diffused organic color reflection
  ctx.save();
  ctx.scale(1, -0.32);
  ctx.translate(0, -scale * 0.55);
  ctx.beginPath();
  ctx.ellipse(0, 0, scale * 0.58, scale * 0.22, 0, 0, Math.PI * 2);

  let reflColor = 'rgba(30, 41, 59, 0.28)';
  if (species === 'mallard') {
    reflColor = gender === 'male' ? 'rgba(6, 78, 59, 0.35)' : 'rgba(69, 26, 3, 0.3)';
  } else if (species === 'mandarin') {
    reflColor = 'rgba(124, 45, 18, 0.32)';
  } else if (species === 'pochard') {
    reflColor = 'rgba(122, 28, 18, 0.3)';
  }

  ctx.fillStyle = reflColor;
  ctx.filter = 'blur(5px)';
  ctx.fill();
  ctx.restore();

  ctx.restore();
}

/**
 * Naturalistic webbed feet seen submerged in clear water
 */
function drawRealisticFeet(
  ctx: CanvasRenderingContext2D,
  scale: number,
  species: DuckSpeciesId,
  phase: number,
  isUpEnding: boolean
) {
  ctx.save();
  ctx.globalAlpha = 0.65;

  let footColor = '#475569';
  if (species === 'mallard') footColor = '#EA580C'; // Bright orange Mallard web
  else if (species === 'mandarin') footColor = '#F97316';
  else if (species === 'teal') footColor = '#64748B'; // Slate grey

  const offset1 = Math.sin(phase) * scale * 0.11;
  const offset2 = Math.sin(phase + Math.PI) * scale * 0.11;

  const yBase = isUpEnding ? -scale * 0.08 : scale * 0.22;

  // Far paddle
  ctx.fillStyle = footColor;
  ctx.beginPath();
  ctx.ellipse(-scale * 0.14 + offset1, yBase, scale * 0.07, scale * 0.038, 0.25, 0, Math.PI * 2);
  ctx.fill();

  // Near paddle
  ctx.beginPath();
  ctx.ellipse(-scale * 0.04 + offset2, yBase + scale * 0.02, scale * 0.075, scale * 0.04, 0.15, 0, Math.PI * 2);
  ctx.fill();

  ctx.restore();
}

/**
 * Photorealistic bird body with anatomical feather tracts, scapulars, and fine vermiculations
 */
function drawRealisticBody(
  ctx: CanvasRenderingContext2D,
  scale: number,
  duck: DuckEntity
) {
  const { species, gender, paddlePhase } = duck;
  const isMale = gender === 'male';

  ctx.save();

  // --- 1. Organic Anatomical Body Contour Path ---
  ctx.beginPath();
  // Forechest curving gently into breast
  ctx.moveTo(scale * 0.15, -scale * 0.12);
  ctx.bezierCurveTo(scale * 0.48, -scale * 0.08, scale * 0.55, scale * 0.12, scale * 0.32, scale * 0.19);
  // Underbelly submerged along waterline
  ctx.bezierCurveTo(scale * 0.05, scale * 0.22, -scale * 0.28, scale * 0.21, -scale * 0.58, scale * 0.1);
  // Pointed tail tip & retrices
  ctx.bezierCurveTo(-scale * 0.72, 0.02, -scale * 0.74, -scale * 0.06, -scale * 0.62, -scale * 0.14);
  // Rump and dorsal back slope towards neck base
  ctx.bezierCurveTo(-scale * 0.42, -scale * 0.21, -scale * 0.12, -scale * 0.22, scale * 0.15, -scale * 0.12);
  ctx.closePath();

  // --- 2. Species-Specific Realistic Feather Pigmentation ---
  let bodyGrad = ctx.createLinearGradient(-scale * 0.7, 0, scale * 0.52, 0);

  if (species === 'mallard') {
    if (isMale) {
      // Wild Mallard Drake: Jet velvet undertail, pure white tail margins, silver-grey vermiculated flanks,
      // and deep iridescent chocolate-claret breast.
      bodyGrad.addColorStop(0.0, '#09090B'); // Velvet black undertail
      bodyGrad.addColorStop(0.14, '#F8FAFC'); // Stark white outer tail feathers
      bodyGrad.addColorStop(0.28, '#CBD5E1'); // Silver grey vermiculated flank
      bodyGrad.addColorStop(0.68, '#E2E8F0');
      bodyGrad.addColorStop(0.76, '#78350F'); // Deep claret / chestnut breast
      bodyGrad.addColorStop(1.0, '#451A03');
    } else {
      // Wild Mallard Hen: Cryptic mottled plumage, buff and umber
      bodyGrad.addColorStop(0.0, '#451A03');
      bodyGrad.addColorStop(0.3, '#78350F');
      bodyGrad.addColorStop(0.65, '#92400E');
      bodyGrad.addColorStop(1.0, '#78350F');
    }
  } else if (species === 'pochard') {
    if (isMale) {
      // Common Pochard Drake: Jet black breast and rump, finely penciled ash-grey body
      bodyGrad.addColorStop(0.0, '#09090B'); // Jet black rump
      bodyGrad.addColorStop(0.22, '#334155');
      bodyGrad.addColorStop(0.36, '#E2E8F0'); // Pale pearl-grey back & flanks
      bodyGrad.addColorStop(0.72, '#CBD5E1');
      bodyGrad.addColorStop(0.8, '#1E293B');
      bodyGrad.addColorStop(1.0, '#09090B'); // Jet black breast
    } else {
      bodyGrad.addColorStop(0.0, '#292524');
      bodyGrad.addColorStop(0.5, '#57534E');
      bodyGrad.addColorStop(1.0, '#44403C');
    }
  } else if (species === 'tufted') {
    if (isMale) {
      // Tufted Duck Drake: High-contrast pure snow-white flanks framed by obsidian-black
      bodyGrad.addColorStop(0.0, '#09090B');
      bodyGrad.addColorStop(0.24, '#0F172A');
      bodyGrad.addColorStop(0.3, '#FFFFFF'); // Pristine white flank panel
      bodyGrad.addColorStop(0.7, '#FFFFFF');
      bodyGrad.addColorStop(0.76, '#0F172A');
      bodyGrad.addColorStop(1.0, '#09090B');
    } else {
      bodyGrad.addColorStop(0.0, '#1C1917');
      bodyGrad.addColorStop(0.5, '#44403C');
      bodyGrad.addColorStop(1.0, '#292524');
    }
  } else if (species === 'mandarin') {
    if (isMale) {
      // Mandarin Drake: Apricot flanks, wine-purple breast, dark charcoal back
      bodyGrad.addColorStop(0.0, '#1C1917');
      bodyGrad.addColorStop(0.2, '#D97706'); // Warm apricot-gold flank
      bodyGrad.addColorStop(0.5, '#FDE68A');
      bodyGrad.addColorStop(0.72, '#581C87'); // Rich imperial purple breast
      bodyGrad.addColorStop(1.0, '#3B0764');
    } else {
      bodyGrad.addColorStop(0.0, '#374151');
      bodyGrad.addColorStop(0.5, '#6B7280');
      bodyGrad.addColorStop(1.0, '#4B5563');
    }
  } else if (species === 'teal') {
    if (isMale) {
      // Eurasian Teal Drake: Cream vent patch, finely penciled silver flank, buff speckled breast
      bodyGrad.addColorStop(0.0, '#09090B');
      bodyGrad.addColorStop(0.12, '#FEF08A'); // Iconic creamy-yellow undertail patch
      bodyGrad.addColorStop(0.28, '#CBD5E1'); // Silver grey vermiculations
      bodyGrad.addColorStop(0.72, '#94A3B8');
      bodyGrad.addColorStop(1.0, '#64748B'); // Speckled breast
    } else {
      bodyGrad.addColorStop(0.0, '#292524');
      bodyGrad.addColorStop(0.5, '#57534E');
      bodyGrad.addColorStop(1.0, '#78716C');
    }
  }

  ctx.fillStyle = bodyGrad;
  ctx.fill();

  // Subtle 3D volumetric shading: top highlight from sun, bottom bounce light from water
  const volumeGrad = ctx.createLinearGradient(0, -scale * 0.22, 0, scale * 0.2);
  volumeGrad.addColorStop(0, 'rgba(255, 255, 255, 0.12)');
  volumeGrad.addColorStop(0.6, 'transparent');
  volumeGrad.addColorStop(1, 'rgba(15, 23, 42, 0.22)');
  ctx.fillStyle = volumeGrad;
  ctx.fill();

  // --- 3. Microscopic Plumage Vermiculations & Scallop Patterns ---
  if (isMale && (species === 'mallard' || species === 'pochard' || species === 'teal')) {
    ctx.save();
    ctx.clip();
    ctx.strokeStyle = 'rgba(71, 85, 105, 0.32)';
    ctx.lineWidth = 0.75;
    // Over 50 ultra-fine wavy pencil strokes across the flank
    for (let x = -scale * 0.35; x < scale * 0.28; x += 2.6) {
      ctx.beginPath();
      const wave1 = Math.sin(x * 14 + paddlePhase) * 1.8;
      const wave2 = Math.cos(x * 18) * 1.2;
      ctx.moveTo(x, -scale * 0.14 + wave1);
      ctx.lineTo(x + 1.8, scale * 0.14 + wave2);
      ctx.stroke();
    }
    ctx.restore();
  }

  // Cryptic mottled feathers on female ducks
  if (!isMale) {
    ctx.save();
    ctx.clip();
    ctx.fillStyle = 'rgba(41, 37, 36, 0.35)';
    for (let i = 0; i < 28; i++) {
      const fx = -scale * 0.45 + (i % 7) * (scale * 0.12);
      const fy = -scale * 0.1 + Math.floor(i / 7) * (scale * 0.06);
      ctx.beginPath();
      ctx.arc(fx, fy, scale * 0.024, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  }

  // --- 4. Authentic Wing Speculum with Real Photonic Luster ---
  drawRealisticSpeculum(ctx, scale, species, isMale);

  ctx.restore();
}

/**
 * Authentic iridescent speculum wing patch
 */
function drawRealisticSpeculum(
  ctx: CanvasRenderingContext2D,
  scale: number,
  species: DuckSpeciesId,
  isMale: boolean
) {
  ctx.save();

  if (species === 'mallard') {
    // Mallard: Intense cobalt-violet iridescent speculum flanked by crisp white bars and black margins
    const sx = -scale * 0.34;
    const sy = -scale * 0.09;
    const sw = scale * 0.19;
    const sh = scale * 0.065;

    // Outer white wing bar
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(sx - 1.5, sy - 1.5, sw + 3, sh + 3);

    // Black framing bar
    ctx.fillStyle = '#09090B';
    ctx.fillRect(sx - 0.5, sy - 0.5, sw + 1, sh + 1);

    // Iridescent cobalt-to-purple center
    const specGrad = ctx.createLinearGradient(sx, sy, sx + sw, sy);
    specGrad.addColorStop(0, '#1D4ED8'); // Cobalt blue
    specGrad.addColorStop(0.5, '#4338CA'); // Indigo
    specGrad.addColorStop(1, '#6D28D9'); // Purple luster
    ctx.fillStyle = specGrad;
    ctx.fillRect(sx, sy, sw, sh);
  } else if (species === 'teal') {
    // Eurasian Teal: Vivid metallic emerald green speculum bordered with pale yellow
    const sx = -scale * 0.3;
    const sy = -scale * 0.08;
    const sw = scale * 0.16;
    const sh = scale * 0.055;

    ctx.fillStyle = '#FEF08A';
    ctx.fillRect(sx - 1, sy - 1, sw + 2, sh + 2);

    const tealSpec = ctx.createLinearGradient(sx, sy, sx + sw, sy);
    tealSpec.addColorStop(0, '#047857');
    tealSpec.addColorStop(0.6, '#059669');
    tealSpec.addColorStop(1, '#10B981');
    ctx.fillStyle = tealSpec;
    ctx.fillRect(sx, sy, sw, sh);
  } else if (species === 'mandarin' && isMale) {
    // Mandarin: Dual vertical white flank accents framing purple breast
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(scale * 0.16, -scale * 0.12, scale * 0.024, scale * 0.17);
    ctx.fillRect(scale * 0.22, -scale * 0.1, scale * 0.024, scale * 0.15);
  }

  ctx.restore();
}

/**
 * Species-defining natural features:
 * - Curled central tail retrices of the wild Mallard drake ("drake curls")
 * - Mandarin orange fan sails (modified inner tertials)
 * - Drooping silky crest of the Tufted Duck
 */
function drawRealisticSpeciesAccents(
  ctx: CanvasRenderingContext2D,
  scale: number,
  duck: DuckEntity,
  timeMs: number
) {
  const { species, gender } = duck;
  const isMale = gender === 'male';

  ctx.save();

  if (species === 'mallard' && isMale) {
    // Central Drake Curls: Pair of jet black glossy feathers tightly curled upward
    ctx.beginPath();
    ctx.moveTo(-scale * 0.62, -scale * 0.06);
    ctx.bezierCurveTo(-scale * 0.76, -scale * 0.19, -scale * 0.58, -scale * 0.25, -scale * 0.54, -scale * 0.14);
    ctx.strokeStyle = '#09090B';
    ctx.lineWidth = 2.8;
    ctx.lineCap = 'round';
    ctx.stroke();

    // Subtle green sheen on the curve
    ctx.beginPath();
    ctx.arc(-scale * 0.65, -scale * 0.16, 2, 0, Math.PI * 2);
    ctx.fillStyle = '#059669';
    ctx.fill();
  } else if (species === 'mandarin' && isMale) {
    // Upright Fan Sail Feathers: Spectacular copper-orange tertials held vertically
    const flutter = Math.sin(timeMs * 0.004) * 0.04;
    ctx.save();
    ctx.translate(-scale * 0.24, -scale * 0.19);
    ctx.rotate(-0.28 + flutter);

    // Primary sail
    ctx.beginPath();
    ctx.moveTo(0, 0);
    ctx.lineTo(-scale * 0.1, -scale * 0.35); // Sharp triangular tip
    ctx.bezierCurveTo(scale * 0.06, -scale * 0.3, scale * 0.14, -scale * 0.16, scale * 0.11, 0);
    ctx.closePath();

    const sailGrad = ctx.createLinearGradient(0, 0, 0, -scale * 0.35);
    sailGrad.addColorStop(0, '#C2410C');
    sailGrad.addColorStop(0.7, '#EA580C');
    sailGrad.addColorStop(0.92, '#F97316');
    sailGrad.addColorStop(1, '#FEF3C7'); // Ivory pale tip
    ctx.fillStyle = sailGrad;
    ctx.fill();

    // Fine feather vane striations
    ctx.strokeStyle = '#9A3412';
    ctx.lineWidth = 0.8;
    for (let v = 1; v <= 4; v++) {
      ctx.beginPath();
      ctx.moveTo(0, 0);
      ctx.lineTo(scale * (0.02 * v - 0.08), -scale * (0.08 * v));
      ctx.stroke();
    }

    // Secondary smaller sail
    ctx.beginPath();
    ctx.moveTo(-scale * 0.05, 0);
    ctx.lineTo(-scale * 0.14, -scale * 0.28);
    ctx.lineTo(-scale * 0.03, -scale * 0.16);
    ctx.closePath();
    ctx.fillStyle = '#9A3412';
    ctx.fill();

    ctx.restore();
  }

  ctx.restore();
}

/**
 * Photorealistic Head, Neck, Eyes and Bill:
 * - Structural iridescent green head for Mallard with optical highlight
 * - Moist liquid eye with dark limbal ring, iris color, pupil, and sky catchlight
 * - Anatomical bill with culmen, lateral slope, and dark terminal nail
 */
function drawRealisticHead(
  ctx: CanvasRenderingContext2D,
  scale: number,
  duck: DuckEntity,
  headNod: number,
  isDabbling: boolean
) {
  const { species, gender } = duck;
  const isMale = gender === 'male';

  ctx.save();
  const neckX = scale * 0.28;
  const neckY = -scale * 0.12 + headNod;
  ctx.translate(neckX, neckY);

  // --- 1. Realistic Neck Musculature ---
  ctx.beginPath();
  ctx.moveTo(-scale * 0.09, scale * 0.12);
  ctx.bezierCurveTo(-scale * 0.07, -scale * 0.12, -scale * 0.05, -scale * 0.26, scale * 0.01, -scale * 0.4);
  ctx.lineTo(scale * 0.14, -scale * 0.36);
  ctx.bezierCurveTo(scale * 0.13, -scale * 0.18, scale * 0.15, 0, scale * 0.09, scale * 0.12);
  ctx.closePath();

  let neckColor = '#18181B';
  if (species === 'mallard') {
    neckColor = isMale ? '#064E3B' : '#78350F';
  } else if (species === 'pochard') {
    neckColor = isMale ? '#991B1B' : '#57534E';
  } else if (species === 'mandarin') {
    neckColor = isMale ? '#C2410C' : '#475569';
  } else if (species === 'teal') {
    neckColor = isMale ? '#991B1B' : '#57534E';
  } else if (species === 'tufted') {
    neckColor = isMale ? '#09090B' : '#292524';
  }

  ctx.fillStyle = neckColor;
  ctx.fill();

  // Mallard White Neck Collar Ring (crisp 1.8mm white band dividing green from claret)
  if (species === 'mallard' && isMale) {
    ctx.beginPath();
    ctx.moveTo(-scale * 0.06, 0.01);
    ctx.lineTo(scale * 0.12, 0.01);
    ctx.strokeStyle = '#FFFFFF';
    ctx.lineWidth = 2.2;
    ctx.stroke();
  }

  // --- 2. Head Silhouette & Structural Photonic Iridescence ---
  const headCenterX = scale * 0.05;
  const headCenterY = -scale * 0.46;

  ctx.beginPath();
  ctx.ellipse(headCenterX, headCenterY, scale * 0.165, scale * 0.145, -0.06, 0, Math.PI * 2);

  if (species === 'mallard' && isMale) {
    // Mallard Drake Head: Dual-stop structural interference
    // Shifts dynamically between deep peacock teal, metallic emerald, and gold sheen on the crown
    const mallardHead = ctx.createRadialGradient(
      headCenterX + scale * 0.04,
      headCenterY - scale * 0.05,
      scale * 0.01,
      headCenterX,
      headCenterY,
      scale * 0.18
    );
    mallardHead.addColorStop(0, '#34D399'); // Sunlit crown highlight
    mallardHead.addColorStop(0.35, '#059669'); // Metallic emerald
    mallardHead.addColorStop(0.75, '#064E3B'); // Peacock teal
    mallardHead.addColorStop(1.0, '#022c22'); // Indigo-black shadow at nape
    ctx.fillStyle = mallardHead;
  } else if (species === 'pochard' && isMale) {
    // Common Pochard: Glowing rich chestnut-russet reddish head
    const pochardHead = ctx.createRadialGradient(
      headCenterX + scale * 0.04,
      headCenterY - scale * 0.04,
      scale * 0.01,
      headCenterX,
      headCenterY,
      scale * 0.18
    );
    pochardHead.addColorStop(0, '#DC2626');
    pochardHead.addColorStop(0.45, '#B91C1C');
    pochardHead.addColorStop(0.85, '#7F1D1D');
    pochardHead.addColorStop(1.0, '#450A0A');
    ctx.fillStyle = pochardHead;
  } else if (species === 'tufted' && isMale) {
    // Tufted Drake: Obsidian black with delicate royal purple shimmer on the cheeks
    const tuftedHead = ctx.createRadialGradient(
      headCenterX + scale * 0.04,
      headCenterY - scale * 0.04,
      scale * 0.01,
      headCenterX,
      headCenterY,
      scale * 0.18
    );
    tuftedHead.addColorStop(0, '#2E1065'); // Royal purple sheen
    tuftedHead.addColorStop(0.4, '#0F172A');
    tuftedHead.addColorStop(1.0, '#09090B');
    ctx.fillStyle = tuftedHead;
  } else if (species === 'mandarin' && isMale) {
    // Mandarin: Copper-chestnut cheeks and deep green-violet crest
    ctx.fillStyle = '#9A3412';
  } else if (species === 'teal' && isMale) {
    // Teal: Rich chestnut with glossy green eye mask
    ctx.fillStyle = '#991B1B';
  } else {
    // Female mottled brown
    ctx.fillStyle = '#57534E';
  }
  ctx.fill();

  // --- 3. Species Head Ornaments & Crests ---
  // A. Tufted Duck Drooping Silky Crest
  if (species === 'tufted' && isMale) {
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(headCenterX - scale * 0.12, headCenterY);
    ctx.bezierCurveTo(
      headCenterX - scale * 0.26, headCenterY + scale * 0.03,
      headCenterX - scale * 0.34, headCenterY + scale * 0.16,
      headCenterX - scale * 0.28, headCenterY + scale * 0.26 // Long silky drooping tip
    );
    ctx.strokeStyle = '#09090B';
    ctx.lineWidth = 3.6;
    ctx.lineCap = 'round';
    ctx.stroke();

    // Second thinner plume filament
    ctx.beginPath();
    ctx.moveTo(headCenterX - scale * 0.11, headCenterY + scale * 0.02);
    ctx.bezierCurveTo(
      headCenterX - scale * 0.24, headCenterY + scale * 0.06,
      headCenterX - scale * 0.3, headCenterY + scale * 0.18,
      headCenterX - scale * 0.24, headCenterY + scale * 0.24
    );
    ctx.strokeStyle = '#1E1B4B';
    ctx.lineWidth = 2.0;
    ctx.stroke();
    ctx.restore();
  }

  // B. Eurasian Teal Metallic Green Mask Patch
  if (species === 'teal' && isMale) {
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(headCenterX + scale * 0.05, headCenterY - scale * 0.02);
    ctx.bezierCurveTo(
      headCenterX - scale * 0.02, headCenterY - scale * 0.08,
      headCenterX - scale * 0.14, headCenterY - scale * 0.04,
      headCenterX - scale * 0.16, headCenterY + scale * 0.04
    );
    ctx.bezierCurveTo(
      headCenterX - scale * 0.09, headCenterY + scale * 0.08,
      headCenterX - scale * 0.01, headCenterY + scale * 0.04,
      headCenterX + scale * 0.05, headCenterY - scale * 0.02
    );
    ctx.closePath();
    ctx.fillStyle = '#047857'; // Deep emerald
    ctx.fill();
    ctx.strokeStyle = '#FEF08A'; // Delicate creamy outline
    ctx.lineWidth = 0.9;
    ctx.stroke();
    ctx.restore();
  }

  // C. Mandarin Sweeping White Facial Crescent
  if (species === 'mandarin' && isMale) {
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(headCenterX + scale * 0.06, headCenterY - scale * 0.03);
    ctx.bezierCurveTo(
      headCenterX - scale * 0.04, headCenterY - scale * 0.11,
      headCenterX - scale * 0.2, headCenterY - scale * 0.09,
      headCenterX - scale * 0.28, headCenterY + scale * 0.07
    );
    ctx.strokeStyle = '#FFFFFF';
    ctx.lineWidth = 4.2;
    ctx.lineCap = 'round';
    ctx.stroke();
    ctx.restore();
  }

  // --- 4. Anatomical Bill / Beak with Nostril Fossa & Terminal Nail ---
  drawRealisticBill(ctx, scale, species, isMale, headCenterX, headCenterY);

  // --- 5. Photorealistic Liquid Wildlife Eye ---
  drawRealisticEye(ctx, scale, species, isMale, headCenterX, headCenterY);

  ctx.restore();
}

/**
 * Anatomical bird bill:
 * Includes natural culmen curvature, lateral slope, nostril opening (fossa), and dark terminal nail.
 */
function drawRealisticBill(
  ctx: CanvasRenderingContext2D,
  scale: number,
  species: DuckSpeciesId,
  isMale: boolean,
  hx: number,
  hy: number
) {
  const bX = hx + scale * 0.11;
  const bY = hy - scale * 0.02;

  ctx.save();

  // Natural culmen slope and tip nail
  ctx.beginPath();
  ctx.moveTo(bX, bY - scale * 0.042);
  ctx.lineTo(bX + scale * 0.185, bY - scale * 0.008); // Bill tip
  ctx.lineTo(bX + scale * 0.165, bY + scale * 0.042); // Lower gape
  ctx.lineTo(bX - scale * 0.02, bY + scale * 0.042);
  ctx.closePath();

  if (species === 'mallard') {
    if (isMale) {
      // Natural olive-yellow bill with green undertones
      const billGrad = ctx.createLinearGradient(bX, bY, bX + scale * 0.18, bY);
      billGrad.addColorStop(0, '#CA8A04');
      billGrad.addColorStop(0.5, '#EAB308');
      billGrad.addColorStop(1, '#FACC15');
      ctx.fillStyle = billGrad;
    } else {
      // Female: Mottled orange with dark center saddle
      ctx.fillStyle = '#D97706';
    }
  } else if (species === 'pochard') {
    // Pochard: Distinctive tri-color pattern — black base, slate-blue central saddle, black tip
    const pochardBill = ctx.createLinearGradient(bX, 0, bX + scale * 0.185, 0);
    pochardBill.addColorStop(0, '#09090B'); // Black base
    pochardBill.addColorStop(0.28, '#09090B');
    pochardBill.addColorStop(0.38, '#64748B'); // Pale slate-blue band
    pochardBill.addColorStop(0.68, '#94A3B8');
    pochardBill.addColorStop(0.78, '#09090B'); // Black tip
    pochardBill.addColorStop(1.0, '#09090B');
    ctx.fillStyle = pochardBill;
  } else if (species === 'tufted') {
    // Tufted Duck: Broad slate-blue bill with black nail
    const tuftedBill = ctx.createLinearGradient(bX, 0, bX + scale * 0.185, 0);
    tuftedBill.addColorStop(0, '#475569');
    tuftedBill.addColorStop(0.65, '#94A3B8');
    tuftedBill.addColorStop(0.78, '#09090B'); // Black nail
    ctx.fillStyle = tuftedBill;
  } else if (species === 'mandarin') {
    // Mandarin: Coral red with pale horn tip
    const mandBill = ctx.createLinearGradient(bX, 0, bX + scale * 0.185, 0);
    mandBill.addColorStop(0, '#DC2626');
    mandBill.addColorStop(0.75, '#EF4444');
    mandBill.addColorStop(1.0, '#FEF3C7');
    ctx.fillStyle = mandBill;
  } else {
    // Teal: Dark slate grey
    ctx.fillStyle = '#334155';
  }
  ctx.fill();

  // Dark terminal nail (unguis) at bill tip
  ctx.beginPath();
  ctx.ellipse(bX + scale * 0.175, bY + scale * 0.012, 2.2, 1.8, 0, 0, Math.PI * 2);
  ctx.fillStyle = '#09090B';
  ctx.fill();

  // Anatomical nostril fossa (longitudinal dark slit)
  ctx.beginPath();
  ctx.ellipse(bX + scale * 0.07, bY - scale * 0.005, scale * 0.02, 0.9, -0.1, 0, Math.PI * 2);
  ctx.fillStyle = '#09090B';
  ctx.fill();

  ctx.restore();
}

/**
 * Photorealistic wildlife eye:
 * Includes dark limbal ring, colored iris with radial gradient, crisp black pupil,
 * sky specular catchlight reflection, and soft secondary water bounce light.
 */
function drawRealisticEye(
  ctx: CanvasRenderingContext2D,
  scale: number,
  species: DuckSpeciesId,
  isMale: boolean,
  hx: number,
  hy: number
) {
  const eX = hx + scale * 0.05;
  const eY = hy - scale * 0.045;
  const radius = scale * 0.025;

  ctx.save();

  // 1. Dark limbal outer ring
  ctx.beginPath();
  ctx.arc(eX, eY, radius + 0.5, 0, Math.PI * 2);
  ctx.fillStyle = '#09090B';
  ctx.fill();

  // 2. Realistic species iris
  ctx.beginPath();
  ctx.arc(eX, eY, radius, 0, Math.PI * 2);

  if (species === 'pochard' && isMale) {
    // Brilliant ruby-red iris of the Pochard Drake
    const rubyIris = ctx.createRadialGradient(eX, eY, radius * 0.2, eX, eY, radius);
    rubyIris.addColorStop(0, '#EF4444');
    rubyIris.addColorStop(0.6, '#DC2626');
    rubyIris.addColorStop(1, '#991B1B');
    ctx.fillStyle = rubyIris;
  } else if (species === 'tufted' && isMale) {
    // Glowing amber-yellow eye of the Tufted Drake
    const yellowIris = ctx.createRadialGradient(eX, eY, radius * 0.2, eX, eY, radius);
    yellowIris.addColorStop(0, '#FEF08A');
    yellowIris.addColorStop(0.7, '#FACC15');
    yellowIris.addColorStop(1, '#CA8A04');
    ctx.fillStyle = yellowIris;
  } else {
    // Liquid dark hazel-brown iris for Mallard, Mandarin, Teal
    const brownIris = ctx.createRadialGradient(eX, eY, radius * 0.2, eX, eY, radius);
    brownIris.addColorStop(0, '#78350F');
    brownIris.addColorStop(0.8, '#451A03');
    brownIris.addColorStop(1, '#1C1917');
    ctx.fillStyle = brownIris;
  }
  ctx.fill();

  // 3. Deep black pupil
  ctx.beginPath();
  ctx.arc(eX, eY, radius * 0.48, 0, Math.PI * 2);
  ctx.fillStyle = '#000000';
  ctx.fill();

  // 4. Primary optical sky specular catchlight reflection (ultra-crisp pinprick)
  ctx.beginPath();
  ctx.arc(eX + radius * 0.28, eY - radius * 0.32, radius * 0.28, 0, Math.PI * 2);
  ctx.fillStyle = '#FFFFFF';
  ctx.fill();

  // 5. Subtle secondary water bounce reflection at bottom of cornea
  ctx.beginPath();
  ctx.arc(eX - radius * 0.2, eY + radius * 0.32, radius * 0.16, 0, Math.PI * 2);
  ctx.fillStyle = 'rgba(224, 242, 254, 0.65)';
  ctx.fill();

  ctx.restore();
}

/**
 * Waterline meniscus with natural surface tension and V-wake
 */
function drawRealisticWaterline(
  ctx: CanvasRenderingContext2D,
  scale: number
) {
  ctx.save();
  // Delicate translucent meniscus line wetting the plumage
  ctx.beginPath();
  ctx.ellipse(scale * 0.02, scale * 0.16, scale * 0.58, scale * 0.038, 0, 0, Math.PI * 2);
  ctx.strokeStyle = 'rgba(255, 255, 255, 0.45)';
  ctx.lineWidth = 1.1;
  ctx.stroke();

  // Gentle bow wave ripple at breast
  ctx.beginPath();
  ctx.arc(scale * 0.45, scale * 0.15, scale * 0.08, -Math.PI * 0.35, Math.PI * 0.35);
  ctx.strokeStyle = 'rgba(224, 242, 254, 0.55)';
  ctx.lineWidth = 1.4;
  ctx.stroke();
  ctx.restore();
}
