import { PochardEntity, PochardPlumage, WaterRipple, Breadcrumb } from '../types';

/**
 * Draws realistic water ripples and wakes generated by the swimming pochard
 */
export function drawWaterRipples(
  ctx: CanvasRenderingContext2D,
  ripples: WaterRipple[],
  width: number,
  height: number
) {
  for (const ripple of ripples) {
    const rx = ripple.x * width;
    const ry = ripple.y * height;
    const radiusX = ripple.radius * width;
    const radiusY = radiusX * (ripple.aspectRatio || 0.45); // Elliptical perspective on water surface

    ctx.save();
    ctx.beginPath();
    ctx.ellipse(rx, ry, radiusX, radiusY, 0, 0, Math.PI * 2);

    const strokeColor = ripple.color || `rgba(255, 255, 255, ${ripple.alpha.toFixed(3)})`;
    ctx.strokeStyle = strokeColor;
    ctx.lineWidth = Math.max(1, 2.5 * ripple.alpha);
    ctx.stroke();

    // Subtle inner aqua shimmer
    ctx.beginPath();
    ctx.ellipse(rx, ry, radiusX * 0.92, radiusY * 0.92, 0, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(147, 197, 253, ${(ripple.alpha * 0.45).toFixed(3)})`;
    ctx.lineWidth = 1;
    ctx.stroke();

    ctx.restore();
  }
}

/**
 * Draws floating breadcrumbs/seeds
 */
export function drawBreadcrumbs(
  ctx: CanvasRenderingContext2D,
  breadcrumbs: Breadcrumb[],
  width: number,
  height: number
) {
  for (const b of breadcrumbs) {
    const bx = b.x * width;
    const by = b.y * height;
    const alpha = Math.max(0, Math.min(1, b.life));

    ctx.save();
    // Breadcrumb floating ring
    ctx.beginPath();
    ctx.ellipse(bx, by, 7, 3.5, 0, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(254, 240, 138, ${(alpha * 0.6).toFixed(2)})`;
    ctx.lineWidth = 1.5;
    ctx.stroke();

    // Crumb body
    ctx.beginPath();
    ctx.ellipse(bx, by - 1, 3.5, 2.5, 0.2, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(245, 158, 11, ${alpha.toFixed(2)})`;
    ctx.fill();
    ctx.strokeStyle = `rgba(180, 83, 9, ${alpha.toFixed(2)})`;
    ctx.lineWidth = 0.8;
    ctx.stroke();

    ctx.restore();
  }
}

/**
 * Draws an anatomically detailed Pochard diving duck with animations:
 * - Characteristic male chestnut-red head, black breast, silver-grey vermiculated body, tri-colored bill
 * - Female / Red-crested variant plumage
 * - Bobbing on waves, rhythmic head nod, paddling feet, water reflection, and diving plunge
 */
export function drawPochard(
  ctx: CanvasRenderingContext2D,
  pochard: PochardEntity,
  width: number,
  height: number,
  timeMs: number
) {
  const px = pochard.x * width;
  const py = pochard.y * height;
  const scale = (pochard.scale || 1.0) * Math.min(width, height) * 0.16;

  // Behavior-specific transforms
  const isDiving = pochard.behavior === 'diving';
  const isSubmerged = pochard.behavior === 'submerged';
  const isResurfacing = pochard.behavior === 'resurfacing';
  const isDabbling = pochard.behavior === 'dabbling';

  // Floating bobbing motion on water waves
  const waveBob = Math.sin(timeMs * 0.003 + pochard.bobPhase) * (scale * 0.04);
  const headNod = Math.sin(pochard.paddlePhase * 2) * (scale * 0.03);

  // Submerged transparency and vertical offset
  let renderAlpha = 1.0;
  let diveOffset = 0;
  let pitchTilt = 0;

  if (isDiving) {
    const progress = Math.min(1, (1000 - pochard.behaviorTimer) / 1000);
    diveOffset = progress * scale * 0.8;
    pitchTilt = -progress * 0.9; // Head down, tail up tip dive
    renderAlpha = 1.0 - progress * 0.55;
  } else if (isSubmerged) {
    diveOffset = scale * 0.9;
    renderAlpha = 0.35; // Translucent underwater shadow
  } else if (isResurfacing) {
    const progress = Math.min(1, (600 - pochard.behaviorTimer) / 600);
    diveOffset = (1 - progress) * scale * 0.8;
    pitchTilt = (1 - progress) * 0.3;
    renderAlpha = 0.45 + progress * 0.55;
  } else if (isDabbling) {
    pitchTilt = -0.55; // Dipping beak into the water
  }

  ctx.save();
  ctx.translate(px, py + waveBob + diveOffset);

  // Flip horizontally if swimming toward the left
  const isMovingLeft = Math.cos(pochard.angle) < 0;
  ctx.scale(isMovingLeft ? -1 : 1, 1);
  ctx.rotate(pitchTilt * (isMovingLeft ? -1 : 1));

  ctx.globalAlpha = renderAlpha;

  const plumage: PochardPlumage = pochard.gender === 'female' ? 'common_female' : 'common_male';

  // 1. Water Reflection beneath the duck
  drawDuckWaterReflection(ctx, scale, plumage, renderAlpha);

  // 2. Submerged underbody & paddling webbed feet
  if (!isSubmerged) {
    drawSubmergedPaddles(ctx, scale, pochard.paddlePhase);
  }

  // 3. Main Body: Black breast & rear, silvery-grey finely vermiculated back
  drawPochardBody(ctx, scale, plumage, pochard.paddlePhase);

  // 4. Wings & Speculum
  drawPochardWings(ctx, scale, plumage);

  // 5. Head, Neck & Bill with head nodding
  drawPochardHead(ctx, scale, plumage, headNod, isDabbling);

  // 6. Waterline foam / meniscus
  drawWaterlineFoam(ctx, scale, isMovingLeft);

  ctx.restore();
}

/**
 * Water reflection underneath duck
 */
function drawDuckWaterReflection(
  ctx: CanvasRenderingContext2D,
  scale: number,
  plumage: PochardPlumage,
  alpha: number
) {
  ctx.save();
  ctx.scale(1, -0.42); // Mirror vertically and compress
  ctx.translate(0, -scale * 0.12);
  ctx.filter = 'blur(3px)';
  ctx.globalAlpha = alpha * 0.28;

  // Dark reflection silhouette
  ctx.beginPath();
  ctx.ellipse(0, 0, scale * 0.65, scale * 0.32, 0, 0, Math.PI * 2);
  const color = plumage === 'common_female' ? '#4A3728' : '#1E293B';
  ctx.fillStyle = color;
  ctx.fill();

  ctx.restore();
}

/**
 * Webbed feet paddling rhythmically beneath the waterline
 */
function drawSubmergedPaddles(
  ctx: CanvasRenderingContext2D,
  scale: number,
  phase: number
) {
  ctx.save();
  ctx.globalAlpha = 0.45;
  const paddleOffset1 = Math.sin(phase) * scale * 0.12;
  const paddleOffset2 = Math.sin(phase + Math.PI) * scale * 0.12;

  // Dark slate-grey webbed feet of the pochard
  ctx.fillStyle = '#334155';

  // Left foot
  ctx.beginPath();
  ctx.ellipse(-scale * 0.15 + paddleOffset1, scale * 0.22, scale * 0.08, scale * 0.04, 0.3, 0, Math.PI * 2);
  ctx.fill();

  // Right foot
  ctx.beginPath();
  ctx.ellipse(-scale * 0.05 + paddleOffset2, scale * 0.24, scale * 0.08, scale * 0.04, 0.2, 0, Math.PI * 2);
  ctx.fill();

  ctx.restore();
}

/**
 * Pochard body:
 * Characteristic coloration of male Aythya ferina:
 * Jet-black rounded breast, pale silvery-grey flanks and back with fine vermiculations, black rear/vent.
 */
function drawPochardBody(
  ctx: CanvasRenderingContext2D,
  scale: number,
  plumage: PochardPlumage,
  phase: number
) {
  ctx.save();

  const isMale = plumage === 'common_male';
  const isRedCrested = plumage === 'red_crested';

  // --- Breast & Fore-body ---
  ctx.beginPath();
  // Deep rounded chest riding the water
  ctx.moveTo(scale * 0.1, -scale * 0.1);
  ctx.bezierCurveTo(
    scale * 0.52, -scale * 0.05,
    scale * 0.54, scale * 0.18,
    scale * 0.25, scale * 0.2
  );
  ctx.bezierCurveTo(
    -scale * 0.15, scale * 0.22,
    -scale * 0.55, scale * 0.18,
    -scale * 0.65, scale * 0.02
  );
  // Tail point cocked slightly up
  ctx.bezierCurveTo(
    -scale * 0.72, -scale * 0.05,
    -scale * 0.6, -scale * 0.16,
    -scale * 0.35, -scale * 0.18
  );
  ctx.bezierCurveTo(
    -scale * 0.1, -scale * 0.2,
    scale * 0.05, -scale * 0.2,
    scale * 0.1, -scale * 0.1
  );
  ctx.closePath();

  // Flank base color
  let flankGradient = ctx.createLinearGradient(-scale * 0.6, 0, scale * 0.5, 0);
  if (isMale) {
    flankGradient.addColorStop(0.0, '#0F172A'); // Black rear
    flankGradient.addColorStop(0.2, '#1E293B');
    flankGradient.addColorStop(0.35, '#E2E8F0'); // Silvery grey vermiculated flank
    flankGradient.addColorStop(0.7, '#CBD5E1');
    flankGradient.addColorStop(0.78, '#1E293B'); // Jet black breast starts
    flankGradient.addColorStop(1.0, '#09090B');
  } else if (isRedCrested) {
    flankGradient.addColorStop(0.0, '#1C1917');
    flankGradient.addColorStop(0.25, '#F8FAFC'); // Striking white flank panel
    flankGradient.addColorStop(0.7, '#F8FAFC');
    flankGradient.addColorStop(0.8, '#1C1917'); // Black belly/breast
    flankGradient.addColorStop(1.0, '#0C0A09');
  } else {
    // Female Common Pochard: mottled grey-brown
    flankGradient.addColorStop(0.0, '#3E2723');
    flankGradient.addColorStop(0.3, '#6D4C41');
    flankGradient.addColorStop(0.65, '#8D6E63');
    flankGradient.addColorStop(1.0, '#4E342E');
  }

  ctx.fillStyle = flankGradient;
  ctx.fill();

  // Subtle fine vermiculation texture (characteristic ripples on Pochard flanks)
  if (isMale) {
    ctx.save();
    ctx.clip();
    ctx.strokeStyle = 'rgba(100, 116, 139, 0.32)';
    ctx.lineWidth = 1;
    for (let x = -scale * 0.35; x < scale * 0.25; x += 3.5) {
      ctx.beginPath();
      const wave = Math.sin(x * 12 + phase) * 2;
      ctx.moveTo(x, -scale * 0.15 + wave);
      ctx.lineTo(x + 2, scale * 0.15 + wave);
      ctx.stroke();
    }
    ctx.restore();
  }

  // Black rear tail feathers
  ctx.beginPath();
  ctx.moveTo(-scale * 0.55, 0);
  ctx.lineTo(-scale * 0.74, -scale * 0.08); // Tail tip
  ctx.lineTo(-scale * 0.65, scale * 0.02);
  ctx.closePath();
  ctx.fillStyle = isFemalePlumage(plumage) ? '#3E2723' : '#09090B';
  ctx.fill();

  ctx.restore();
}

function isFemalePlumage(plumage: PochardPlumage) {
  return plumage === 'common_female';
}

/**
 * Wing Speculum and mantle feathers
 */
function drawPochardWings(
  ctx: CanvasRenderingContext2D,
  scale: number,
  plumage: PochardPlumage
) {
  ctx.save();

  const isMale = plumage === 'common_male';
  const isRedCrested = plumage === 'red_crested';

  // Folded wing along the flank
  ctx.beginPath();
  ctx.moveTo(-scale * 0.1, -scale * 0.18);
  ctx.bezierCurveTo(
    scale * 0.15, -scale * 0.18,
    scale * 0.25, -scale * 0.05,
    scale * 0.05, scale * 0.04
  );
  ctx.bezierCurveTo(
    -scale * 0.25, scale * 0.06,
    -scale * 0.5, -scale * 0.02,
    -scale * 0.62, -scale * 0.1
  );
  ctx.closePath();

  if (isMale) {
    ctx.fillStyle = 'rgba(203, 213, 225, 0.45)';
    ctx.strokeStyle = '#475569';
  } else if (isRedCrested) {
    ctx.fillStyle = '#57534E';
    ctx.strokeStyle = '#292524';
  } else {
    ctx.fillStyle = '#5D4037';
    ctx.strokeStyle = '#3E2723';
  }
  ctx.lineWidth = 1;
  ctx.fill();
  ctx.stroke();

  ctx.restore();
}

/**
 * Pochard Head, Neck, Bill and distinctive Ruby Red Eye:
 * - Male Common Pochard: rich chestnut/copper reddish head, triangular high forehead sloping gently into bill
 * - Bill: dark base, pale blue-grey central band, black nail tip
 * - Eye: ruby red with black pupil
 */
function drawPochardHead(
  ctx: CanvasRenderingContext2D,
  scale: number,
  plumage: PochardPlumage,
  headNod: number,
  isDabbling: boolean
) {
  ctx.save();

  // Head origin anchored to neck
  const neckX = scale * 0.28;
  const neckY = -scale * 0.12 + headNod;
  ctx.translate(neckX, neckY);

  const isMale = plumage === 'common_male';
  const isRedCrested = plumage === 'red_crested';

  // --- Neck ---
  ctx.beginPath();
  ctx.moveTo(-scale * 0.08, scale * 0.12);
  ctx.bezierCurveTo(
    -scale * 0.06, -scale * 0.12,
    -scale * 0.04, -scale * 0.25,
    scale * 0.02, -scale * 0.38
  );
  ctx.lineTo(scale * 0.15, -scale * 0.35);
  ctx.bezierCurveTo(
    scale * 0.12, -scale * 0.18,
    scale * 0.14, 0,
    scale * 0.08, scale * 0.12
  );
  ctx.closePath();

  // Male neck: lower part black, upper part rich chestnut
  const neckGradient = ctx.createLinearGradient(0, scale * 0.1, 0, -scale * 0.35);
  if (isMale) {
    neckGradient.addColorStop(0, '#09090B'); // Blends into black breast
    neckGradient.addColorStop(0.35, '#1E293B');
    neckGradient.addColorStop(0.65, '#882218'); // Chestnut-red
    neckGradient.addColorStop(1.0, '#A63324');
  } else if (isRedCrested) {
    neckGradient.addColorStop(0, '#0C0A09');
    neckGradient.addColorStop(0.5, '#EA580C'); // Orange-chestnut
    neckGradient.addColorStop(1.0, '#F97316');
  } else {
    neckGradient.addColorStop(0, '#4E342E');
    neckGradient.addColorStop(1.0, '#795548');
  }
  ctx.fillStyle = neckGradient;
  ctx.fill();

  // --- Head Profile ---
  // High peaked crown with characteristic sloping forehead
  ctx.beginPath();
  const headCenterX = scale * 0.06;
  const headCenterY = -scale * 0.45;

  if (isRedCrested) {
    // Round puffy crest
    ctx.ellipse(headCenterX - scale * 0.02, headCenterY, scale * 0.18, scale * 0.16, -0.15, 0, Math.PI * 2);
    ctx.fillStyle = '#EA580C';
    ctx.fill();
  } else {
    // Common Pochard peaked forehead profile
    ctx.moveTo(headCenterX - scale * 0.1, headCenterY + scale * 0.08);
    ctx.bezierCurveTo(
      headCenterX - scale * 0.14, headCenterY - scale * 0.08, // Nape
      headCenterX - scale * 0.05, headCenterY - scale * 0.16, // Crown
      headCenterX + scale * 0.08, headCenterY - scale * 0.15  // Forehead peak
    );
    // Smooth slope down to bill
    ctx.bezierCurveTo(
      headCenterX + scale * 0.16, headCenterY - scale * 0.08,
      headCenterX + scale * 0.18, headCenterY,
      headCenterX + scale * 0.12, headCenterY + scale * 0.08
    );
    ctx.bezierCurveTo(
      headCenterX + scale * 0.05, headCenterY + scale * 0.12,
      headCenterX - scale * 0.04, headCenterY + scale * 0.12,
      headCenterX - scale * 0.1, headCenterY + scale * 0.08
    );
    ctx.closePath();

    const headGradient = ctx.createRadialGradient(
      headCenterX + scale * 0.04, headCenterY - scale * 0.06, scale * 0.02,
      headCenterX, headCenterY, scale * 0.2
    );

    if (isMale) {
      headGradient.addColorStop(0, '#D95B3B'); // Warm coppery highlight
      headGradient.addColorStop(0.4, '#BA3D2A'); // Rich chestnut-red
      headGradient.addColorStop(1.0, '#7A1C12'); // Deep mahogany shadow
    } else {
      headGradient.addColorStop(0, '#A1887F');
      headGradient.addColorStop(0.6, '#6D4C41');
      headGradient.addColorStop(1.0, '#4E342E');
    }
    ctx.fillStyle = headGradient;
    ctx.fill();
  }

  // --- Bill (Beak) ---
  // Sloping long bill. For male Common Pochard: black at base, broad pale blue-grey band, black tip nail
  ctx.save();
  const billStartX = headCenterX + scale * 0.12;
  const billStartY = headCenterY - scale * 0.02;

  ctx.beginPath();
  ctx.moveTo(billStartX, billStartY - scale * 0.05);
  ctx.lineTo(billStartX + scale * 0.18, billStartY - scale * 0.01); // Tip
  ctx.lineTo(billStartX + scale * 0.16, billStartY + scale * 0.04);
  ctx.lineTo(billStartX - scale * 0.02, billStartY + scale * 0.04);
  ctx.closePath();

  if (isRedCrested) {
    // Bright scarlet-red bill!
    ctx.fillStyle = '#DC2626';
    ctx.fill();
    ctx.strokeStyle = '#991B1B';
    ctx.stroke();
  } else if (isMale) {
    // Multi-tone Aythya ferina bill
    const billGradient = ctx.createLinearGradient(
      billStartX, 0, billStartX + scale * 0.18, 0
    );
    billGradient.addColorStop(0.0, '#1E293B'); // Dark base
    billGradient.addColorStop(0.25, '#334155');
    billGradient.addColorStop(0.35, '#94A3B8'); // Distinctive pale blue-grey saddle band
    billGradient.addColorStop(0.75, '#CBD5E1');
    billGradient.addColorStop(0.85, '#1E293B'); // Black nail tip
    billGradient.addColorStop(1.0, '#09090B');

    ctx.fillStyle = billGradient;
    ctx.fill();
    ctx.strokeStyle = 'rgba(15, 23, 42, 0.6)';
    ctx.lineWidth = 0.8;
    ctx.stroke();
  } else {
    // Female bill: dark slate grey with faint pale subterminal band
    const billGradient = ctx.createLinearGradient(
      billStartX, 0, billStartX + scale * 0.18, 0
    );
    billGradient.addColorStop(0.0, '#263238');
    billGradient.addColorStop(0.5, '#546E7A');
    billGradient.addColorStop(1.0, '#263238');
    ctx.fillStyle = billGradient;
    ctx.fill();
  }
  ctx.restore();

  // --- Eye ---
  // In male Common Pochard: vivid ruby red eye with small black pupil
  const eyeX = headCenterX + scale * 0.05;
  const eyeY = headCenterY - scale * 0.05;
  const eyeRadius = scale * 0.024;

  ctx.beginPath();
  ctx.arc(eyeX, eyeY, eyeRadius, 0, Math.PI * 2);

  if (isMale || isRedCrested) {
    ctx.fillStyle = '#E11D48'; // Vivid ruby red iris
    ctx.fill();

    // Tiny bright highlight
    ctx.beginPath();
    ctx.arc(eyeX + 0.5, eyeY - 0.5, eyeRadius * 0.35, 0, Math.PI * 2);
    ctx.fillStyle = '#FFFFFF';
    ctx.fill();

    // Dark central pupil
    ctx.beginPath();
    ctx.arc(eyeX, eyeY, eyeRadius * 0.45, 0, Math.PI * 2);
    ctx.fillStyle = '#09090B';
    ctx.fill();
  } else {
    // Female brown eye with faint pale ring
    ctx.fillStyle = '#4E342E';
    ctx.fill();
    ctx.beginPath();
    ctx.arc(eyeX, eyeY, eyeRadius * 0.4, 0, Math.PI * 2);
    ctx.fillStyle = '#1A1A1A';
    ctx.fill();
  }

  ctx.restore();
}

/**
 * Waterline froth and surface meniscus where feathers meet the water
 */
function drawWaterlineFoam(
  ctx: CanvasRenderingContext2D,
  scale: number,
  isMovingLeft: boolean
) {
  ctx.save();
  // Delicate water surface meniscus
  ctx.beginPath();
  ctx.ellipse(scale * 0.02, scale * 0.16, scale * 0.58, scale * 0.05, 0, 0, Math.PI * 2);
  ctx.strokeStyle = 'rgba(255, 255, 255, 0.4)';
  ctx.lineWidth = 1.5;
  ctx.stroke();

  // Small bow wave ripple at the chest
  ctx.beginPath();
  ctx.arc(scale * 0.45, scale * 0.15, scale * 0.1, -Math.PI * 0.4, Math.PI * 0.4);
  ctx.strokeStyle = 'rgba(224, 242, 254, 0.7)';
  ctx.lineWidth = 2;
  ctx.stroke();

  ctx.restore();
}
